# Generated by Django 5.1.4 on 2024-12-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('calle', models.TextField(max_length=40, null=True)),
                ('colonia', models.TextField(max_length=40, null=True)),
                ('numero_int', models.PositiveIntegerField(max_length=5, null=True)),
                ('numero_ext', models.PositiveIntegerField(max_length=5, null=True)),
                ('cp', models.PositiveIntegerField(max_length=5, null=True)),
            ],
        ),
    ]
