# Generated by Django 5.1.4 on 2024-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='cp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='numero_ext',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='numero_int',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
