# Generated by Django 5.1.4 on 2025-01-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_rename_place_address_user_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='calle',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='colonia',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='numero_ext',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Working'), (2, 'Price Ready'), (3, 'Pickup Ready'), (4, 'Closed')])),
                ('has_half', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List_Of_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
