# Generated by Django 5.1.4 on 2025-01-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_address_calle_alter_address_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_at_home',
            field=models.BooleanField(default=False),
        ),
    ]
