# Generated by Django 5.1.4 on 2025-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_pick_up_at_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_to',
        ),
        migrations.AddField(
            model_name='order',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nueva'), (1, 'Abierta'), (2, 'Cerrada'), (3, 'Lista'), (4, 'Terminada')], default=0),
        ),
    ]
