# Generated by Django 5.1.4 on 2025-01-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_from_order_date_remove_order_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
