# Generated by Django 5.1.4 on 2025-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_tinto_others_order_total_list_of_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_tinto',
            field=models.IntegerField(null=True),
        ),
    ]
