# Generated by Django 5.1.4 on 2025-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_total_tinto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tinto',
        ),
        migrations.AlterField(
            model_name='list_of_others',
            name='concept',
            field=models.TextField(max_length=100),
        ),
    ]
