# Generated by Django 5.1.4 on 2025-01-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_total_remove_order_total_tinto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_others',
            name='amount',
        ),
        migrations.AddField(
            model_name='list_of_others',
            name='price',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
