# Generated by Django 5.1.4 on 2025-02-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_list_of_others_amount_list_of_others_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_payment',
            field=models.BooleanField(default=False),
        ),
    ]
