# Generated by Django 5.1.4 on 2025-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_card_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_order',
            name='price_dryclean_due',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_of_order',
            name='price_due',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
