# Generated by Django 5.1.4 on 2025-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_list_of_order_price_dryclean_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tinto_paid',
            field=models.BooleanField(default=False),
        ),
    ]
