# Generated by Django 5.1.4 on 2025-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_tinto_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(null=True),
        ),
    ]
