# Generated by Django 5.1.4 on 2025-02-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dryclean_balance_dryclean_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='numero_int',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dryclean_movements',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tinto_others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_dryclean',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
