# Generated by Django 5.1.4 on 2025-02-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_address_cp_alter_address_numero_int_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Spending_movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.spending_categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Dryclean_balance',
        ),
    ]
