# Generated by Django 5.1.4 on 2025-02-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_spending_categories_spending_movements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending_movements',
            name='category',
            field=models.TextField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Spending_categories',
        ),
    ]
