# Generated by Django 5.1.4 on 2025-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_spending_movements_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tinto_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='opened_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
