# Generated by Django 5.1.4 on 2025-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_order_tinto_paid_order_opened_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending_movements',
            name='card_payment',
            field=models.BooleanField(default=False),
        ),
    ]
