# Generated by Django 5.1.4 on 2025-02-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_spending_movements_card_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivered',
        ),
    ]
