# Generated by Django 5.1.4 on 2025-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_order_date_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Half_Load_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
            ],
        ),
    ]
