# Generated by Django 5.1.4 on 2025-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_half_load_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='has_half',
            field=models.SmallIntegerField(default=0),
        ),
    ]
