# Generated by Django 5.1.4 on 2025-02-17 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_has_half'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('country_code', models.DecimalField(decimal_places=0, max_digits=3)),
                ('unicode_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(62), django.core.validators.MaxValueValidator(87)])),
                ('unicode_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(62), django.core.validators.MaxValueValidator(87)])),
            ],
        ),
    ]
