# Generated by Django 5.1.4 on 2025-02-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country_code',
        ),
    ]
