# Generated by Django 5.1.4 on 2025-02-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_country_code_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_code',
            old_name='country_code',
            new_name='phone',
        ),
    ]
