# Generated by Django 5.1.4 on 2025-02-19 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_country_code_country_code_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountinvited', to='api.order')),
                ('discount_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountreference', to='api.order')),
                ('invited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
