# Generated by Django 5.1.4 on 2025-02-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recommendation',
            name='value_invited',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_recommendation',
            name='value_reference',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_recommendation',
            name='discount_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountinvited', to='api.order'),
        ),
        migrations.AlterField(
            model_name='user_recommendation',
            name='discount_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountreference', to='api.order'),
        ),
    ]
