# Generated by Django 5.1.4 on 2025-03-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_star_discount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nueva'), (1, 'Abierta'), (2, 'Cerrada'), (3, 'Lista'), (4, 'Terminada'), (5, 'Eliminada')], default=0),
        ),
    ]
