# Generated by Django 5.1.4 on 2025-03-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending_movements',
            name='card_payment',
        ),
        migrations.AddField(
            model_name='spending_movements',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Efectivo'), (1, 'Tarjeta'), (2, 'Caja')], default=0),
        ),
    ]
