# Generated by Django 5.1.4 on 2025-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_spending_movements_card_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('amount_left', models.IntegerField()),
            ],
        ),
    ]
